[package]
name = "sqlx-scylladb-example-basic"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0.99"
sqlx = "0.8.6"
sqlx-scylladb = { path = "../../sqlx-scylladb", features = ["migrate", "any"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
